import type { Metadata} from "next";
import Link from "next/link";
import Image from "next/image"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

//meta
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


//font
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <nav className="navigation">
          <div className="logo"><Link href={"/"}>conquest</Link></div>
          <div className="nav_list">
            <div className="nav_item">
              <Link href="/posts/new">
                <div className="nav_contant">
                  <Image src="/assets/nav_2.png" alt="navpng2"/>
                  <div>글 작성</div>
                </div>
              </Link>
            </div>
            <div className="nav_item">
              <Link href="/mypage">
                <div className="nav_contant">
                  <Image src="/assets/nav_1.png" alt="navpng1"/>
                  <div>마이페이지</div>
                </div>
              </Link>
            </div>
          </div>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
