import type { Metadata} from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

//meta
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


//font
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <nav className="navigation">
          <div className="logo"><Link href={"/"}>conquest</Link></div>
          <ul className="nav_list">
            <li><Link href="/articles">글 작성</Link></li>
            <li><Link href="/contact">마이페이지</Link></li>
          </ul>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
